services:
  phoenix:
    container_name: phoenix
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/app
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-pcrm_dev}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-db}
      MIX_ENV: ${MIX_ENV:-dev}
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-pcrm_dev}
    restart: always
